server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cambio_db
    username: postgres
    password: 311005Ge
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/cambio_db
    user: postgres
    password: 311005Ge
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  api-docs:
    path: /cambio-service/v3/api-docs
