server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      findByIdAndCurrency:
        minimum-number-of-calls: 4
        sliding-window-size: 8
      findAllProdCatalog:
        minimum-number-of-calls: 4
        sliding-window-size: 8
      findById:
         minimum-number-of-calls: 4
         sliding-window-size: 8
      findAllCircuit:
         minimum-number-of-calls: 4
         sliding-window-size: 8
spring:
  sql:
    init:
      mode: always
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-store-db
    username: postgres
    password: 311005Ge
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: /product-service/v3/api-docs