server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      findByIdAndCurrency:
        minimum-number-of-calls: 4
        sliding-window-size: 8
      findAllProdCatalog:
        minimum-number-of-calls: 4
        sliding-window-size: 8
      findById:
         minimum-number-of-calls: 4
         sliding-window-size: 8
      findAllCircuit:
         minimum-number-of-calls: 4
         sliding-window-size: 8
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products_microservices?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/products_microservices?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin123
  rabbitmq:
    host: localhost
    port: 5672 
    username: guest
    password: guest
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: /product-service/v3/api-docs